defaults:
  - hydra: default
  - model: dyn_unet_base
  - _self_

# i/o
#image_path: "/home/hvv/Documents/nnunet_folder/nnUNet_raw/Dataset519_AV_cta/imagesTr"
#image_path: "/media/hvv/ec2480e5-6c18-468c-b971-5271432b386d/hvv/raw_CTP_melbourne/processed/time_averages"
image_path: "/media/hvv/71672b1c-e082-495c-b560-a2dfc7d5de59/data/raw_CTP_melbourne/cta_crisp2/cta"
image_file_ending: nii.gz
#output_folder: "/media/hvv/71672b1c-e082-495c-b560-a2dfc7d5de59/data/raw_CTP_melbourne/cta_crisp2/cta_Dataset509_CTAvseg"
#output_folder: "/media/hvv/ec2480e5-6c18-468c-b971-5271432b386d/hvv/raw_CTP_melbourne/processed/519_vesselFM_cta"
#output_folder: "/media/hvv/ec2480e5-6c18-468c-b971-5271432b386d/hvv/raw_CTP_melbourne/processed/521_vesselFM_ta"
output_folder: '/media/hvv/71672b1c-e082-495c-b560-a2dfc7d5de59/data/vesselFM/test_fold_0'
file_app: ""

mask_path: null
round_to: 2

# model & ckpt
device: cuda:0
ckpt_path: /media/hvv/71672b1c-e082-495c-b560-a2dfc7d5de59/data/vesselFM/checkpoints/vesselfm/finetune_3shot_hvv_vesselfm/finetune_3shot_hvv_vesselfm_last.ckpt

# sliding window inferer
batch_size: 8
patch_size: [128, 128, 128]
overlap: 0.5
mode: "constant"
sigma_scale: 0.125
padding_mode: "constant"

# eval & reproducibility
seed: 404

# standard pre-processing transforms
transforms_config:
  - EnsureChannelFirst:
      channel_dim: "no_channel"
  - ScaleIntensityRangePercentiles:
      lower: 1
      upper: 99
      b_min: 0
      b_max: 1
      clip: true
  - ToTensor:
      device: null

# test time augmentation
tta:
  scales: [1] #[0.5, 1, 1.5]
  invert: false
  invert_mean_thresh: 0.5
  equalize_hist: false
  hist_bins: 100

# post-processing
post:
  apply: false
  small_objects_min_size: 500
  small_objects_connectivity: 3

# merging
merging:
  threshold: 0.5
  max: false